### PR TITLE
Add rpc-websockets

### PR DESCRIPTION
**Pull request by mkozjak**

### CODE REVIEW

**Comment by mkozjak** [comment]
@Kikobeats what about this one?

**Comment by Kikobeats** [comment]
when I investigate a bit more about that 🙂

**Comment by karliky** [comment]
Is this gonna be merged?

**Comment by mkozjak** [comment]
@Kikobeats: Need any help with it?

**Comment by mkozjak** [comment]
Thanks, @Kikobeats!

**Pull request merged**
